---
title: "A guide to readable visualizations"
author: "UC Davis Bioinformatics Core"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Excellent visualizations are not only accessible, but clear and concise. The following guide outlines our current understanding of best practices for creating high-impact, easily interpreted figures.

# Background

Relatively little research has been done on the role of visual representation of data in scientific literature. Instead, we extrapolate guidelines from studies focusing on visual communication in news media, marketing materials, and the financial sector, as well as principles of web and application development. The work of Edward Tufte and that of the Nielsen Norman group informed many of the conclusions drawn here, and may be of use to interested readers.

# Why adhere to "best practices?"

Research on data visualization in news media and finance suggests that decreasing the work involved in understanding findings improves engagement from readers. Edward Tufte suggests that proper use of graphics, instead of tables, to display materials data, could have prevented the *Columbia* space shuttle disaster. Nielsen Norman group reports that strategic use of graphical elements improves user comprehension of website and applications design, resulting in increased task success in testing. Though we do not yet have experimental data to support the claim, anecdotes suggest that superior visualizations can make the difference between publishing in prestigious journals and being declined.

# Principles of visual design

## Color

The first consideration with color choice should be ease of perception for colorblind individuals, but designing an effective color palette does not stop with selecting a "colorblind-friendly" library.

Color is typically the most prominent visual characteristic of a graphic; color choices send strong signals to the reader and should be selected accordingly.

- use color sparingly and intentionally
- use color consistently across graphics
- use a small number of colors
- use the brightest / most notable color for the items of greatest interest
- keep cultural significance of colors in mind

### "Start with gray"

This advice comes from Jonathan Schwabish's *Better Data Visualizations*. By starting with a gray-scale visualization, we can use color selectively to highlight the data of interest and avoid bombarding readers with data of lower relevance to the conclusions presented.

## Scale

Although pie charts are notoriously difficult to interpret correctly, size and area are strong signals that can be used to add another dimension to a graphic. In many visualizations, there is a direct link between size and the value of the data represented (e.g. the height of bars in a bar chart). If possible, avoid using size for categorical values that do not have a relationship to quantity, as this can be misleading and create unneccesary confusion. Additionally, it is important to keep in mind that larger elements are typically perceived as more significant when creating a multi-panel figure.

## Shape

Color alone is often insufficient to express the full range of information to be communicated by a graphic. A second useful dimension is shape. Shape is particularly valuable with categorical variables that do not have a natural relationship to quantity, frequency, or other numerical values.

- again, be sparing and consistent
- things with the same shape will be perceived as similar

## Heirarchy

Items with greater perceived visual importance will be viewed first. Additionally, there is a preference to read from top down and left to right.

## Contrast

Contrast (of color, shape, size, shading, etc) conveys difference, and increases the perceived importance of a finding.

## Gestalt: proximity, similarity, and common region

Human brains are adept at finding pattern in visual data. Graphic elements that are close to one another, or contained within a "common region" (e.g. a box bordered by a thin black line) are assumed to be related. This tendency to attribute significance to discovered patterns, whether or not the meaning is supported by the text of axes, legends, and captions, is the primary reason for exercising caution in selecting visual elements and composing multi-panel visualizations. The goal is to create graphics where these patterns reinforce the explicit keys to interpretation provided by textual elements.

## Annotations and call-outs

Annotating a graphic reduces the labor of comprehension by explicitly highlighting critical components. This can take the form of asterisks marking significant comparisons on a bar chart, labels on histological sections highlighting structures of interest, or enclosures grouping samples together, for example.


